function jsLoadDataInToLS() {
    localStorage.setItem("grains", '[{"id":"1","grain_type":"American Rahr - 2 Row Malt","grain_yield":"80","grain_specific_gravity":"1.036","grain_ppg":"36","grain_max_usage":"100","grain_color":"2"},{"id":"3","grain_type":"Best Malz German Munich Malt","grain_yield":"80","grain_specific_gravity":"1.037","grain_ppg":"37","grain_max_usage":"100","grain_color":"6"},{"id":"2","grain_type":"Briess - Caramel 40L Malt","grain_yield":"75","grain_specific_gravity":"1.035","grain_ppg":"35","grain_max_usage":"15","grain_color":"40"},{"id":"9","grain_type":"Briess - Caramel Malt 20L","grain_yield":"75","grain_specific_gravity":"1.035","grain_ppg":"35","grain_max_usage":"15","grain_color":"20"},{"id":"7","grain_type":"Briess - Caramel Malt 80L","grain_yield":"75","grain_specific_gravity":"1.035","grain_ppg":"35","grain_max_usage":"15","grain_color":"80"},{"id":"10","grain_type":"Briess Chocolate Malt","grain_yield":"60","grain_specific_gravity":"1.025","grain_ppg":"25","grain_max_usage":"10","grain_color":"350"},{"id":"15","grain_type":"Brown Sugar","grain_yield":"100","grain_specific_gravity":"1.045","grain_ppg":"45","grain_max_usage":"10","grain_color":"15"},{"id":"11","grain_type":"Crisp English Roasted Barley Malt","grain_yield":"70","grain_specific_gravity":"1.03128","grain_ppg":"31.28","grain_max_usage":"10","grain_color":"500"},{"id":"5","grain_type":"Flaked Oats","grain_yield":"80","grain_specific_gravity":"1.033","grain_ppg":"33","grain_max_usage":"30","grain_color":"2"},{"id":"8","grain_type":"Simpsons - Black Malt","grain_yield":"70","grain_specific_gravity":"1.034","grain_ppg":"34","grain_max_usage":"10","grain_color":"625"},{"id":"6","grain_type":"Simpsons - Chocolate Malt","grain_yield":"73","grain_specific_gravity":"1.032","grain_ppg":"32","grain_max_usage":"20","grain_color":"444"},{"id":"4","grain_type":"Simpsons - Maris Otter Malt","grain_yield":"82","grain_specific_gravity":"1.038","grain_ppg":"38","grain_max_usage":"100","grain_color":"3"}]');

    localStorage.setItem("yeast", '[{"id":"1","yeast_name":"Safale US-05 Ale Dry Yeast","yeast_type":"ale yeast","yeast_form":"dry yeast","yeast_min_temp":"53.6","yeast_max_temp":"77","yeast_attenuation":"75","yeast_dosage":"11.5g in 20 to 30 liters"}]');

    localStorage.setItem("priming_sugars", '[{"id":"4","priming_sugars_name":"Corn Sugar","priming_sugars_notes":"Main Priming Sugar"}]');

    localStorage.setItem("hops", '[{"id":"3","hop_name":"Citra Hops","hop_alpha_acidity":"High (10 %)","hop_form":"Pellets","hop_aroma_and_notes":"Usage: Flavor and Aroma Flavor Profile: grapefruit, mango, pineapple, papaya, peach, apricot, passion fruit, lime, melon, gooseberry, lychee fruit Similar Hop Varieties: Simcoe, Cascade, Centennial, Mosaic Beer Styles (most likely to be used in): India Pale Ale, Pale Ale"},{"id":"8","hop_name":"East Kent Goldings","hop_alpha_acidity":"Medium (5-10%)","hop_form":"Pellets","hop_aroma_and_notes":"Classic English aroma hop. Sweet, spicy floral aroma. Use in all English beers: pale ale, brown ale, porter, stout."},{"id":"2","hop_name":"New Zealand Wakatu","hop_alpha_acidity":"Medium (5-10%)","hop_form":"Pellets","hop_aroma_and_notes":"Characterized by moderate bittering and restrained floral notes atop freshly zested lime."},{"id":"1","hop_name":"US Northern Brewer","hop_alpha_acidity":"Medium (5-10%)","hop_form":"Pellets","hop_aroma_and_notes":"Northern Brewer hops are dual purpose with unique woody, minty notes. This is the signature hop of California Commons. Northern Brewer hops are used in the brewing of ESB, bitter, English pale ale, porters, and California (steam) beer."},{"id":"4","hop_name":"Willamette","hop_alpha_acidity":"Medium (5-10%)","hop_form":"Pellets","hop_aroma_and_notes":"This very popular aroma hop provides an earthy, spicy character to your home brewed English or American ales. Typical alpha: 4.0-6.0%. American-grown seedless version of Fuggle. Willamette hop is a ideal for brewing pale ale, ESB, bitter, English-style ale, porter, and stout"}]');

    localStorage.setItem("extras", '[{"id":"5","extras_name":"Brown Sugar","extras_notes":"Gravity is 1.046"},{"id":"6","extras_name":"None","extras_notes":"Not adding any extras"},{"id":"2","extras_name":"Raspberries","extras_notes":"Used in my IPA Recipe"},{"id":"3","extras_name":"Strawberries ","extras_notes":"Used in the Blonde Ale Recipe"},{"id":"1","extras_name":"Vanilla Bean","extras_notes":"Used in my Stout Recipe"}]');

    localStorage.setItem("recipes", '[{"id":"1","rname":"TanEllens Strawberry Blonde Ale","grains":"7usFor1+0.5usFor9+1usFor15","hops":"0.5usFor4","extras":"2.75usFor3","yeast":"1usFor1","priming_sugars":"1usFor4","batch_size":"2.5 Gallons","abv":"7.09%","descrpition":"This a blonde ale that Jo and I are going to try and make. Strawberries seemed to be a cheap fruit and it will make for a fun beer."},{"id":"2","rname":"Porter Recipe","grains":"6usFor1+1usFor5+0.5usFor10+0.5usFor11","hops":"1usFor1+0.5usFor4+1usFor8","extras":"0usFor6","yeast":"1usFor1","priming_sugars":"1usFor4","batch_size":"2.5 Gallons","abv":"6.5%","descrpition":"The first porter I shall try. Difference between porter and a stout is based of the base grain."},{"id":"12","rname":"Oatmeal Stout v1","grains":"4usFor4+0.5usFor5+0.5usFor6+0.5usFor7+0.5usFor8","hops":"1usFor1","extras":"1usFor1","yeast":"1usFor1","priming_sugars":"1usFor4","batch_size":"2.0","abv":"4.46%","descrpition":"The first stout I made. Decided to try and make an oatmeal stout. turned out good with nice flavor but not the alcohol content I was hoping for."},{"id":"13","rname":"Oatmeal Stout v2","grains":"6usFor4+0.5usFor5+0.5usFor6+0.5usFor7+0.5usFor8","hops":"1usFor1","extras":"1usFor1","yeast":"1usFor1","priming_sugars":"1usFor4","batch_size":"2.0","abv":"8.14%","descrpition":"A new version of my first oatmeal stout. Had the alcohol content I wanted and great flavor. Needs to work on carbonation level next(:"},{"id":"14","rname":"Raspberry IPA ","grains":"6usFor1+1usFor2+1usFor3","hops":"1usFor1+2usFor2+1usFor3","extras":"1.5usFor2","yeast":"1usFor1","priming_sugars":"1usFor4","batch_size":"2.0","abv":"8.79%","descrpition":"The first IPA I made. Thought it turned out really well. The IPA flavor wasnt strong and neither were the raspberries but it had good favor and alcohol content was high."}]');
}